server:
  port: 8080

spring:
  application:
    name: helloWorld
  datasource:
    url: jdbc:mysql://localhost:3306/hello?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: root

mybatis:
  mapper-locations:
    - classpath:/mapper/**/*.xml

